# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(684, 738)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.LblStep3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblStep3.setFont(font)
        self.LblStep3.setObjectName("LblStep3")
        self.gridLayout.addWidget(self.LblStep3, 17, 1, 1, 1)
        self.LblPathDest = QtWidgets.QLabel(self.centralwidget)
        self.LblPathDest.setObjectName("LblPathDest")
        self.gridLayout.addWidget(self.LblPathDest, 2, 1, 1, 2)
        self.LblStep2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblStep2.setFont(font)
        self.LblStep2.setObjectName("LblStep2")
        self.gridLayout.addWidget(self.LblStep2, 5, 1, 1, 1)
        self.LblFiles = QtWidgets.QLabel(self.centralwidget)
        self.LblFiles.setObjectName("LblFiles")
        self.gridLayout.addWidget(self.LblFiles, 12, 1, 1, 1)
        self.LblPathSource = QtWidgets.QLabel(self.centralwidget)
        self.LblPathSource.setObjectName("LblPathSource")
        self.gridLayout.addWidget(self.LblPathSource, 8, 1, 1, 1)
        self.LblHelp = QtWidgets.QLabel(self.centralwidget)
        self.LblHelp.setObjectName("LblHelp")
        self.gridLayout.addWidget(self.LblHelp, 15, 1, 1, 1)
        self.LblFormat = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.LblFormat.setFont(font)
        self.LblFormat.setObjectName("LblFormat")
        self.gridLayout.addWidget(self.LblFormat, 20, 1, 1, 2)
        self.LstDirs = QtWidgets.QListView(self.centralwidget)
        self.LstDirs.setObjectName("LstDirs")
        self.gridLayout.addWidget(self.LstDirs, 18, 1, 1, 2)
        self.LinePathDest = QtWidgets.QLineEdit(self.centralwidget)
        self.LinePathDest.setObjectName("LinePathDest")
        self.gridLayout.addWidget(self.LinePathDest, 3, 1, 1, 2)
        self.BtnSkip = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSkip.setEnabled(False)
        self.BtnSkip.setObjectName("BtnSkip")
        self.gridLayout.addWidget(self.BtnSkip, 16, 2, 1, 1)
        self.BtnConvert = QtWidgets.QPushButton(self.centralwidget)
        self.BtnConvert.setEnabled(False)
        self.BtnConvert.setObjectName("BtnConvert")
        self.gridLayout.addWidget(self.BtnConvert, 15, 2, 1, 1)
        self.BtnCreateDest = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCreateDest.setObjectName("BtnCreateDest")
        self.gridLayout.addWidget(self.BtnCreateDest, 1, 1, 1, 1)
        self.LblStep1 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LblStep1.setFont(font)
        self.LblStep1.setObjectName("LblStep1")
        self.gridLayout.addWidget(self.LblStep1, 0, 1, 1, 2)
        self.LstFiles = QtWidgets.QListView(self.centralwidget)
        self.LstFiles.setObjectName("LstFiles")
        self.gridLayout.addWidget(self.LstFiles, 14, 1, 1, 2)
        self.LinePathSource = QtWidgets.QLineEdit(self.centralwidget)
        self.LinePathSource.setEnabled(False)
        self.LinePathSource.setObjectName("LinePathSource")
        self.gridLayout.addWidget(self.LinePathSource, 10, 1, 1, 2)
        self.BtnChooseDest = QtWidgets.QPushButton(self.centralwidget)
        self.BtnChooseDest.setObjectName("BtnChooseDest")
        self.gridLayout.addWidget(self.BtnChooseDest, 1, 2, 1, 1)
        self.LblDest = QtWidgets.QLabel(self.centralwidget)
        self.LblDest.setObjectName("LblDest")
        self.gridLayout.addWidget(self.LblDest, 4, 1, 1, 2)
        self.BtnChooseSource = QtWidgets.QPushButton(self.centralwidget)
        self.BtnChooseSource.setEnabled(False)
        self.BtnChooseSource.setObjectName("BtnChooseSource")
        self.gridLayout.addWidget(self.BtnChooseSource, 7, 1, 1, 2)
        self.LblSource = QtWidgets.QLabel(self.centralwidget)
        self.LblSource.setObjectName("LblSource")
        self.gridLayout.addWidget(self.LblSource, 11, 1, 1, 2)
        self.BtnCards = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCards.setEnabled(False)
        self.BtnCards.setObjectName("BtnCards")
        self.gridLayout.addWidget(self.BtnCards, 19, 1, 1, 1)
        self.BtnStop = QtWidgets.QPushButton(self.centralwidget)
        self.BtnStop.setEnabled(False)
        self.BtnStop.setObjectName("BtnStop")
        self.gridLayout.addWidget(self.BtnStop, 19, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 684, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройка Сада Теней"))
        self.LblStep3.setText(_translate("MainWindow", "Шаг3. Соотнести с карточками"))
        self.LblPathDest.setText(_translate("MainWindow", "ИЛИ введите путь до папки"))
        self.LblStep2.setText(_translate("MainWindow", "Шаг2. Выбор папки с музыкой"))
        self.LblFiles.setText(_translate("MainWindow", "Файлы в папке:"))
        self.LblPathSource.setText(_translate("MainWindow", "Или введите путь до папки"))
        self.LblHelp.setText(_translate("MainWindow", "Файлы в неподходящем формате выделены красным. \n"
"Для конвертации нажмите «Конвертировать»\n"
"Или эти файлы можно пропустить"))
        self.LblFormat.setText(_translate("MainWindow", "Для справки: подходящий формат wav, 16бит, частота 48000 "))
        self.BtnSkip.setText(_translate("MainWindow", "Пропустить"))
        self.BtnConvert.setText(_translate("MainWindow", "Конвертировать"))
        self.BtnCreateDest.setText(_translate("MainWindow", "Создать папку в текущей"))
        self.LblStep1.setText(_translate("MainWindow", "Шаг1. Выбор папки для итоговых файлов"))
        self.BtnChooseDest.setText(_translate("MainWindow", "Выбрать папку"))
        self.LblDest.setText(_translate("MainWindow", "Выбрана папка:"))
        self.BtnChooseSource.setText(_translate("MainWindow", "Выбрать папку"))
        self.LblSource.setText(_translate("MainWindow", "Выбрана папка:"))
        self.BtnCards.setText(_translate("MainWindow", "Начать соотносить"))
        self.BtnStop.setText(_translate("MainWindow", "Прервать"))

